---
kind: Service
apiVersion: v1
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: svc-${NAMESPACE}-${APP_NAME}
  annotations:
    mesosphere.io/creator: admin
spec:
  ports:
    - name: http-${APP_NAME}
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    gus-app: ${APP_NAME}
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: ${APP_NAME}
  labels:
    gus-app: ${APP_NAME}
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      gus-app: ${APP_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        gus-app: ${APP_NAME}
    spec:
      containers:
        - image: ${IMAGE}
          imagePullPolicy: Always
          name: ${APP_NAME}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          # 添加环境变量注入点
          envFrom:
            - configMapRef:
                name: ${APP_NAME}-env  # 动态引用对应ConfigMap
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliyun
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
